name: Deployment Workflow
on: push
jobs:
  - lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/chackout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

  - deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code 
        uses: actions/chackout@v3 
      
      - name: Install NodeJS 
        uses: actions/setup-node@v3 
        with:
          node-version: 18 
      - name: Install dependencies 
        run: npm ci 

      - name: build 
        run npm run build 

      - name: deploy 
        run: echo "Deploying project to aws "
